version: '3'
services:

  backend:
    container_name: cheek_backend
    restart: on-failure
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mysql:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cheek?createDatabaseIfNotExist=true&characterEncoding=UTF-8&profileSql=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cheek
      MYSQL_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev
    command: ["java", "-jar", "/app.jar"]
#    depends_on:
#      - redis
    volumes:
      - ./backend:/app
      - ./backend/target/classes:/app/classes
    expose:
      - "8080:8080"

  #      REDIS_HOST: ${REDIS_HOST}
#      REDIS_PORT: ${REDIS_PORT}
#      MAIL_USERNAME: ${MAIL_USERNAME}
#      MAIL_PASSWORD: ${MAIL_PASSWORD}
#      JWT_SECRET: ${JWT_SECRET}
#      IAM_ACCESS_KEY: ${IAM_ACCESS_KEY}
#      IAM_SECRET_KEY: ${IAM_SECRET_KEY}
#      BUCKET_NAME: ${BUCKET_NAME}
#    env_file:
#      - .env
#    environment:
#      SPRING_DATASOURCE_URL: ${RDS_URL}
#      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
#
#    networks:
#      - cheek_network
