version: "3.8"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./devops/monitoring/grafana/grafana-data:/var/lib/grafana
#      - ./devops/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    user: root

  nginx:
    container_name: nginx
    build:
      context: devops/nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./devops/nginx/nginx_develop.conf:/etc/nginx/nginx.conf
    #        - build_folder:/var/www/frontend
    expose:
      - '80'
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
